### PR TITLE
Check recovery deadline only once

### PR DESCRIPTION
**Pull request by andig**
This PR simplifies checking for `recoveryDeadline` being exceeded.

Note: refactoring the code like this, it seems to indicate that there is something wrong with the usage of `ProtocolRecoveryTimeout`. It's actual value is never used, only checked against being zero. In contrast, `LinkRecoveryTimeout` is used as input to `sleep`.

### CODE REVIEW

**Review by frzifus — COMMENTED** [review]
probably worth investing some time in setting up [golangci-lint](https://github.com/golangci/golangci-lint). This way we should be able to find many more of such corners.

cc @guelfey

**Comment by andig** [comment]
Any feedback on this one? Open bug regarding `ProtocolRecoveryTimeout`?

**Review by hsteidl — APPROVED** [review]
Good improvement, this simplifies a lot. Especially when looking at corner cases like in https://github.com/grid-x/modbus/pull/66 where the conditions started getting difficult.
This also looks functionality-preserving to me!

**Comment by hsteidl** [comment]
@andig I will merge this PR now as preparation for #66. Another discussion for the `ProtocolRecoveryTimeout` problem would be great as this is still weird

**Pull request merged**
