### PR TITLE
Fix staticcheck findings (yoda questions, result not used)

### PR DESCRIPTION
**Pull request by andig**

### CODE REVIEW

**Review by frzifus — APPROVED** [review]

**Comment by andig** [comment]
Ping- ok to merge?

**Comment by andig** [comment]
Ping for review

**Review by frzifus — APPROVED** [review]

**Comment by andig** [comment]
@guelfey @gq0 any chance for merging?

**Review by gq0 — APPROVED** [review]
Thank you for making the changes and I apologize for the delay. I appreciate your patience and understanding.

**Pull request merged**
